import os
from datetime import time

S3_BUCKET = os.environ["S3_BUCKET"]
TWEET_START_TIME = time(int(os.getenv("TWEET_START_TIME", 7)), 0, 0)
TWEET_END_TIME = time(int(os.getenv("TWEET_END_TIME", 21)), 0, 0)
MIN_TWEET_INTERVAL = int(os.getenv("MIN_TWEET_INTERVAL", 5))
MAX_TWEET_INTERVAL = int(os.getenv("MAX_TWEET_INTERVAL", 60*24))
TWITTER_CREDENTIALS_SECRET_ARN = os.environ["TWITTER_CREDENTIALS_SECRET_ARN"]
PROJECT_CODE = os.environ["PROJECT_CODE"]

S3_EXPENSE_QUEUE_KEY = f"{PROJECT_CODE}_TWEET_EXPENSE_QUEUE.json"
S3_EXCEPTION_QUEUE_KEY = f"{PROJECT_CODE}_TWEET_EXCEPTION_QUEUE.json"
S3_PREV_CLAIM_NUMBERS_KEY = f"{PROJECT_CODE}_PREVIOUS_CLAIM_NUMBERS.txt"
EVENTBRIDGE_EVENT_NAME = f"{PROJECT_CODE}_TWEET_SCHEDULE"

MEMBERS_OF_NOTE_IDS_KEY = "MEMBERS_OF_NOTE.json"
GROUP_THRESHOLDS_KEY = "GROUP_THRESHOLDS.json"
TRAVEL_THRESHOLDS_KEY = "TRAVEL_THRESHOLDS.json"
