import os
from datetime import time

S3_BUCKET = os.environ["MPE_S3_BUCKET"]
TWEET_START_TIME = time(os.getenv("TWEET_START_TIME", 7), 0, 0)
TWEET_END_TIME = time(os.getenv("TWEET_END_TIME", 21), 0, 0)
TWITTER_CREDENTIALS_SECRETS_NAME = os.environ["TWITTER_CREDENTIALS_SECRETS_NAME"]
EVENTBRIDGE_EVENT_NAME = os.environ["MPE_EVENT_NAME"]

S3_EXPENSE_QUEUE_KEY = "TWEET_EXPENSE_QUEUE.json"
S3_EXCEPTION_QUEUE_KEY = "TWEET_EXCEPTION_QUEUE.json"
S3_PREV_CLAIM_NUMBERS_KEY = "PREVIOUS_CLAIM_NUMBERS.txt"
MEMBERS_OF_NOTE_IDS_KEY = "MEMBERS_OF_NOTE.json"
GROUP_THRESHOLDS_KEY = "GROUP_THRESHOLDS.json"
TRAVEL_THRESHOLDS_KEY = "TRAVEL_THRESHOLDS.json"
